### ISSUE TITLE
various output files lacking when running --db general

### ISSUE THREAD

**Issue by jolienvanhooff** [faylward/viralrecall#5]
Hi team, 

When trying to run viralrecall on some genomes with both --db GVOG and --db general, I noticed that several output files are lacking for the latter. Notably, it lacks the "*.full_annot.tsv", which is what I am most interested in. I am possibly also interested in viral regions that can be detected based on the generic VOG database, with default settings, but no regions are reported, although I'm not sure what this is caused by. For example, the '.summary.tsv' file is also lacking. Below you find an overview of what is produced with --db general. Note that the hmmscan outputs look okay, as well as the predicted protein sequences.

I hope you can help me finding out what might go wrong here.

Best,
Jolien 

*.faa  
*.markerout
*.pdf (I was using the '-f' flag) 
*.pfamout  
*.vogout  
* .vregion_annot.tsv (no regions reported)

**Comment by faylward** [comment]
Can you try running it with the -c option? That should output full contig/replicon statistics (not just for any viral regions).

**Comment by faylward** [comment]
I updated the code so it should work either way now.

**Comment by jolienvanhooff** [comment]
Hi! 

I cloned the newest version and ran it on my genome, and indeed I now obtain this full_annot.tsv file when running the general database. Thank you!

I still don't see the summery file, for example, is that purposely so? I mean, possibly for the generic database it makes less sense to search for viral regions than for the giant viruses specifically, but still I think it could be interesting. 

Best wishes,
Jolien

**Comment by faylward** [comment]
I've updated it so that a summary file it always output, even if there are no viral regions to summarize (in this case the file will be blank, but the headers will be there).

**Comment by faylward** [comment]
thanks for pointing these out!

**Comment by jolienvanhooff** [comment]
Sounds good, thanks a lot for the updates!
